name: map_memory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  http: ^1.3.0
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/bag.png
    - assets/images/building.png
    - assets/images/car.png
    - assets/images/heart.png
    - assets/images/ice.png
    - assets/images/montain.png
    - assets/images/mouth.png
    - assets/images/music.png
    - assets/images/tree.png
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/logo3.png
    - assets/images/logo4.png
    - assets/images/logo5.png
    - assets/images/logo6.png
    - assets/images/logo7.png
    - assets/images/logo8.png
    - assets/images/logo9.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo8.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo8.png"
